[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.0",
]

[project]
name = "dezrest"
version = "0.1.0"
description = "serve ezbee/dz/de bee via sanic rest"
authors = [
    {name = "ffreemt", email = "yucongo+fmt@gmail.com"},
]
dependencies = [
    "sanic>=22.9.1",
    "logzero>=1.7.0",
    "pybind11>=2.10.1",
    "fasttext @ https://github.com/ffreemt/ezbee/raw/main/data/artifects/fasttext-0.9.2-cp38-cp38-win_amd64.whl",
    "pycld2 @ https://github.com/ffreemt/ezbee/raw/main/data/artifects/pycld2-0.41-cp38-cp38-win_amd64.whl",
    "PyICU @ https://github.com/ffreemt/ezbee/raw/main/data/artifects/PyICU-2.8.1-cp38-cp38-win_amd64.whl",
    "ezbee>=0.1.2",
    "cmat2aset>=0.1.0a7",
]
requires-python = ">=3.8.3"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
